### ISSUE TITLE
Convert a decimal number to a binary number.

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Basic-Python-Programs#54]

**Comment by amirmohammadre** [comment]
Hi @minhaj-313 , Can I work on this ?

**Comment by minhaj-313** [comment]
> Hi @minhaj-313 , Can I work on this ?

Yes, you can work.
First you need to give a Star to this Repository then start working.
Thank you

**Comment by amirmohammadre** [comment]
> > Hi @minhaj-313 , Can I work on this ?
> 
> Yes, you can work. First you need to give a Star to this Repository then start working. Thank you

Thanks Dear @minhaj-313
