### ISSUE TITLE
Find the sum of all odd numbers in a given range.

### ISSUE THREAD

**Issue by minhaj-313** [minhaj-313/Basic-Python-Programs#98]

**Comment by minhaj-313** [comment]
> Hi @minhaj-313 , Can I work on this?

Yes

**Comment by minhaj-313** [comment]
@amirmohammadre First Give a star to this Repository and Start doing Your Contribution with Clean Code.
Thank You.

**Comment by amirmohammadre** [comment]
Thanks @minhaj-313
